WITH ticketline_cte AS (
   
    SELECT   PRODUCTBRAND, PRODUCTNAME, PRODUCTTYPE ,STOREID , DATECLOSED  
    		, sum (NETSALES) NETSALES_TICKETLINE_RF
    		, sum(SALESTAXAMOUNT) SALESTAXAMOUN_TTICKETLINE_RF
    		, sum(EXCISETAXAMOUNT) EXCISETAXAMOUNT_TICKETLINE_RF
			, sum(qty) UNIT_SALES_RF
    FROM {{source('FIVETRAN_DATABASE','ticketline')}}--FIVETRAN_DATABASE.TREEZ_FIVETRAN.TICKETLINE---- ----
    GROUP BY  PRODUCTBRAND, PRODUCTNAME, PRODUCTTYPE , STOREID , DATECLOSED 
    ORDER BY  PRODUCTBRAND, PRODUCTNAME, PRODUCTTYPE ,STOREID , DATECLOSED   
), inventory_cte AS (    
   
    SELECT   PRODUCTBRAND ,PRODUCTNAME, PRODUCTTYPE, STOREID , CAST(START_DATE AS date) START_DATE ,
    		  sum(DESTROYED_UNITS) DESTROYED_UNITS_INVENTORY_RF,sum(RETURNED_UNITS) RETURNED_UNITS_INVENTORY_RF
    		, sum(SOLD_UNITS) SOLD_UNITS_INVENTORY_RF
    		, sum(AVAILABLE_UNITS) AVAILABLE_UNITS_INVENTORY_RF
    		, max(PRICEUNIT) PRICEUNIT_INVENTORY_RF
    		, max(COST_PER_UNIT) COST_PER_UNIT_INVENTORY_RF
    		
    FROM {{source('FIVETRAN_DATABASE','INVENTORY')}}--FIVETRAN_DATABASE.TREEZ_FIVETRAN.INVENTORY----  ----
    GROUP BY PRODUCTBRAND ,PRODUCTNAME, PRODUCTTYPE, STOREID , CAST(START_DATE AS date)
    ORDER BY PRODUCTBRAND ,PRODUCTNAME, PRODUCTTYPE, STOREID ,CAST(START_DATE AS date) desc
), tickeline_subtype AS 
(
	 SELECT   PRODUCTBRAND, PRODUCTNAME, PRODUCTTYPE,PRODUCTSUBTYPE ,STOREID , DATECLOSED 
	 FROM {{source('FIVETRAN_DATABASE','ticketline')}}--FIVETRAN_DATABASE.TREEZ_FIVETRAN.TICKETLINE
	 GROUP BY  PRODUCTBRAND, PRODUCTNAME, PRODUCTTYPE ,PRODUCTSUBTYPE, STOREID , DATECLOSED	 
), maxdate_cte AS 
(
	SELECT max(START_DATE) MAXDATE_RF FROM inventory_cte
)
SELECT ic.PRODUCTBRAND, ic.PRODUCTNAME, ic.PRODUCTTYPE,tsub.PRODUCTSUBTYPE,  cast(ic.STOREID as varchar) STOREID, ic.START_DATE,
		(SELECT MAXDATE_RF FROM maxdate_cte) MAXDATE_RF,
		DESTROYED_UNITS_INVENTORY_RF, RETURNED_UNITS_INVENTORY_RF,SOLD_UNITS_INVENTORY_RF
		, AVAILABLE_UNITS_INVENTORY_RF, PRICEUNIT_INVENTORY_RF, COST_PER_UNIT_INVENTORY_RF
		, tc.UNIT_SALES_RF, tc.NETSALES_TICKETLINE_RF, tc.SALESTAXAMOUN_TTICKETLINE_RF
		, tc.EXCISETAXAMOUNT_TICKETLINE_RF 
FROM inventory_cte ic
left JOIN ticketline_cte tc
	ON ic.PRODUCTBRAND= tc.PRODUCTBRAND AND ic.PRODUCTNAME=tc.PRODUCTNAME AND  ic.PRODUCTTYPE=tc.PRODUCTTYPE
 	AND ic.STOREID=tc.STOREID AND ic.START_DATE=tc.DATECLOSED 
LEFT JOIN tickeline_subtype tsub 
    ON ic.PRODUCTBRAND= tsub.PRODUCTBRAND AND ic.PRODUCTNAME=tsub.PRODUCTNAME AND  ic.PRODUCTTYPE=tsub.PRODUCTTYPE
 	AND ic.STOREID=tsub.STOREID AND ic.START_DATE=tsub.DATECLOSED 
 
 