 WITH ticketline_cte AS (
   
    SELECT   PRODUCTBRAND, PRODUCTNAME, PRODUCTTYPE , PRODUCTSUBTYPE,STOREID , OPEN_DATE  
    		, sum (NETSALES) NETSALES 
    FROM {{source('FIVETRAN_DATABASE','ticketline')}}--FIVETRAN_DATABASE.TREEZ_FIVETRAN.TICKETLINE 
    GROUP BY  PRODUCTBRAND, PRODUCTNAME, PRODUCTTYPE , PRODUCTSUBTYPE,STOREID , OPEN_DATE 
    ORDER BY  PRODUCTBRAND, PRODUCTNAME, PRODUCTTYPE , PRODUCTSUBTYPE,STOREID , OPEN_DATE   
), inventory_cte AS (    
   
    SELECT   PRODUCTBRAND ,PRODUCTNAME, PRODUCTTYPE, STOREID , CAST(START_DATE AS date) START_DATE ,
    		sum (EXCISE_TAX_PER_UNIT) EXCISE_TAX_PER_UNIT,sum(DESTROYED_UNITS) DESTROYED_UNITS,sum(RETURNED_UNITS) RETURNED_UNITS
    FROM {{source('FIVETRAN_DATABASE','INVENTORY')}}--FIVETRAN_DATABASE.TREEZ_FIVETRAN.INVENTORY  
    GROUP BY PRODUCTBRAND ,PRODUCTNAME, PRODUCTTYPE, STOREID , CAST(START_DATE AS date)
    ORDER BY PRODUCTBRAND ,PRODUCTNAME, PRODUCTTYPE, STOREID ,CAST(START_DATE AS date) desc
)
SELECT ic.*,tc.PRODUCTSUBTYPE, tc.NETSALES 
FROM ticketline_cte tc
INNER JOIN inventory_cte ic
	ON tc.PRODUCTBRAND= ic.PRODUCTBRAND AND tc.PRODUCTNAME=ic.PRODUCTNAME AND  tc.PRODUCTTYPE=ic.PRODUCTTYPE
 	AND tc.STOREID=ic.STOREID AND tc.OPEN_DATE=ic.START_DATE 