WITH fct AS 
( 
	SELECT 	CASE WHEN STORE='The Pottery' THEN 297
				 WHEN STORE='Farmacy SB' THEN 137
				 WHEN STORE='Farmacy SA' THEN 269
				 WHEN STORE='Farmacy BK' THEN 272 ELSE 0 END STOREID
			,"DATE-MONTH" DATE,   ROLLING_FCST_DELIVERY_NETSALES
			,ROLLING_FCST_INSTORE_NETSALES,AOP_FCST_INSTORE_NETSALES,AOP_FCST_DELIVERY_NETSALES
	FROM {{source('FIVETRAN_DATABASE','TREEZ_TICKETLINE_FORECAST')}} --FIVETRAN_DATABASE.TREEZ_FIVETRAN.TREEZ_TICKETLINE_FORECAST
), actual AS 
(
SELECT STOREID ,concat(DATE_PART("Year", DATECLOSED),'-', DATE_PART ("MONTH", DATECLOSED), '-01')::DATE DATE
		, Sum(NETSALES) ACTUALSALES  
FROM {{source('FIVETRAN_DATABASE','ticketline')}}--TICKETLINE 
GROUP BY 1,2 
)
SELECT f.*,ACTUALSALES FROM fct  f
LEFT JOIN actual a 
ON f.DATE=a.DATE AND f.STOREID=a.STOREID 