SELECT
		ia.ID ,ia.STOREID ,ia.REASON , ia.BATCH_ID , ia.REVTYPE , ia.PACKAGE_ID , ia.PRODUCT_SUBTYPE , ia.LAST_RETRIEVED_TIMESTAMP 
		, ia.STATE_TRACKING_ID , ia.DATALAKE_DATE , ia.PRODUCT_ID , ia."ACTION" , ia.ADJUSTMENT_DATETIME , ia.PRODUCT_BRAND 
		, ia.ADJUSTMENT_USER , ia."_FIVETRAN_BATCH" , ia.INVENTORY_ID , ia.CREDIT_NOTE_ID , ia.PRODUCT_NAME , ia.INVOICE_LINE_ID 
		, ia.LOCATION_NAME , ia.PRODUCT_TYPE , ia."_FIVETRAN_INDEX" , ia.RETAIL_BRAND , ia."_FIVETRAN_SYNCED" 
		, ia.ADJUSTMENT_POST_EXCISE_COST ,ia.REVEND , ia.ADJUSTMENT_QTY , ia.REV , ia.CURRENT_QTY , ia.ADJUSTMENT_EXCISE_COST , ia.ORIGINAL_QTY 
FROM TREEZ_FIVETRAN.INVENTORY_ADJUSTMENT ia  