 WITH ticketline_cte AS (
   
    SELECT   PRODUCTBRAND, PRODUCTNAME, PRODUCTTYPE , PRODUCTSUBTYPE,STOREID , OPEN_DATE  
    		, sum (NETSALES) NETSALES 
    FROM {{source('FIVETRAN_DATABASE','ticketline')}}--FIVETRAN_DATABASE.TREEZ_FIVETRAN.TICKETLINE 
    GROUP BY  PRODUCTBRAND, PRODUCTNAME, PRODUCTTYPE , PRODUCTSUBTYPE,STOREID , OPEN_DATE 
    ORDER BY  PRODUCTBRAND, PRODUCTNAME, PRODUCTTYPE , PRODUCTSUBTYPE,STOREID , OPEN_DATE   
), inventory_cte AS (    
   
    SELECT   PRODUCTBRAND ,PRODUCTNAME, PRODUCTTYPE, STOREID , CAST(START_DATE AS date) START_DATE ,
    		sum (EXCISE_TAX_PER_UNIT) EXCISE_TAX_PER_UNIT,sum(DESTROYED_UNITS) DESTROYED_UNITS,sum(RETURNED_UNITS) RETURNED_UNITS
    FROM {{source('FIVETRAN_DATABASE','INVENTORY')}}--FIVETRAN_DATABASE.TREEZ_FIVETRAN.INVENTORY  
    GROUP BY PRODUCTBRAND ,PRODUCTNAME, PRODUCTTYPE, STOREID , CAST(START_DATE AS date)
    ORDER BY PRODUCTBRAND ,PRODUCTNAME, PRODUCTTYPE, STOREID ,CAST(START_DATE AS date) desc
)
SELECT ic.*,tc.PRODUCTSUBTYPE, tc.NETSALES 
FROM inventory_cte ic
left JOIN ticketline_cte tc
	ON id.PRODUCTBRAND= tc.PRODUCTBRAND AND ic.PRODUCTNAME=tc.PRODUCTNAME AND  ic.PRODUCTTYPE=tc.PRODUCTTYPE
 	AND ic.STOREID=tc.STOREID AND ic.OPEN_DATE=tc.START_DATE 