version: 2

sources:
  - name: FIVETRAN_DATABASE
    schema: TREEZ_FIVETRAN
    tables:
      - name: ticketline
      - name: TREEZ_TICKETLINE_FORECAST
      - name: INVENTORY
      - name: INVENTORY_ADJUSTMENT
 